name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
    - run: nimble install -y ws asynctools sorta
    - run: nim c -r tests/all.nim
    - run: nim c -d:release -r tests/all.nim
    - run: nim c -d:release --stackTrace:on --opt:speed -d:ssl --app:console --filenames:canonical -o:binance_dumper ./src/main.nim
    - name: Create artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: binance_dumper_${{ matrix.os }}
        path: binance_dumper*